version: '2'

services:
  frontend:
    build:
      context: frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    networks:
      - doses_network
    environment:
      DOSES_POST_ENDPOINT: http://localhost
      DOSES_GET_ENDPOINT: http://doses-api
      DOSES_ENDPOINT_PORT: 5000
    depends_on:
      - doses-api

  doses-api:
    build:
      context: doses-api
      dockerfile: ../doses-api/Dockerfile
    networks:
      - doses_network
    ports:
      - "5000:5000"

networks:
  doses_network:
    external: false
