import "semantic-ui-css/semantic.min.css"
import "./layout.css"
import { Roboto, Lato } from "next/font/google"
import Link from "next/link"

export const metadata = {
  title: "Support Admin",
  description: "Generated by create next app",
}

const lato = Lato({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lato",
})

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${lato.variable} ${roboto.variable}`}>
      <body>
        <div className="globalHeader">
          <div className="logo">Support Admin</div>
        </div>
        <div>
          <div className="subnav">
            <Link className="subnav__item active" href="/doses">
              Doses
            </Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  )
}
