openapi: 3.0.3
info:
  title: AdhereTech Externship - Doses
  description: |-
    This is the API being employed to store and retrieve patient information regarding dosage for the externship project.

  contact:
    email: sampleEmail@email.com
  license:
    name: MIT
  version: 1.0.11
servers:
  - url: TBD

tags:
  - name: dose
    description: Accessing patient's mediciation information

paths:
  /dose:
    post:
      tags:
        - dose
      summary: Add a new patient and medication information
      description: Add a new patient and medication information
      requestBody:
        description: Create new dosage information to store for the patient
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Dose"
      responses:
        "200":
          description: Successful addition
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DoseResponse"
        "400":
          description: Invalid input
  /dose/{dosageId}:
    get:
      tags:
        - dose
      summary: Retrieve patient and medication information
      description: Retrieve patient and medication information using patient ID
      parameters:
        - name: dosageId
          in: path
          description: ID of the dosage to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Succesful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DoseResponse"
        "400":
          description: Invalid input
        "404":
          description: Dosage not found

  /getAllDoses:
    get:
      tags:
        - dose
      summary: Retrieve all doses
      description: Retrieve all stored doses for all patients
      responses:
        "200":
          description: Succesful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetAllDosesResponse"

        "400":
          description: No valid doses

components:
  schemas:
    Dose:
      required:
        - patient
        - medication
      type: object
      properties:
        patient:
          type: string
          example: John
        medication:
          type: string
          example: Levothraxine
        doseTime:
          type: string
          format: date-time
          example: 2023-07-31 12:34:56

    DoseResponse:
      required:
        - id
        - patient
        - medication
        - doseTime
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 100
        patient:
          type: string
          example: John
        medication:
          type: string
          example: Levothraxine
        doseTime:
          type: string
          format: date-time
          example: 2023-07-31 12:34:5

    GetAllDosesResponse:
      required:
        - Doses
      type: object
      properties:
        doses:
          $ref: "#/components/schemas/DoseResponse"
