apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "krakend.fullname" . }}
data:
  config.yaml: |
    ---
    "$schema": https://www.krakend.io/schema/v2.4/krakend.json
    version: 3
    endpoints: []
    extra_config: {}
