apiVersion: v1
kind: Service
metadata:
  name: {{ include "krakend.fullname" . }}
  labels:
    kubernetes.io/ingress.global-static-ip-name: "krakend-externship"
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.externalIP }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "krakend.selectorLabels" . | nindent 4 }}
